services:
  silo_b1:
    build:
      context: ..
      dockerfile: silo-node/Dockerfile
    container_name: silo_b1
    environment:
      - NODE_ID=Silo_B1
      - COORDINATOR_URL=http://10.104.109.87:5000
      - PEERS=Silo_A1,Silo_A2,Silo_A3,Silo_B1,Silo_B2,Silo_B3
      - SHARED_SECRET=class-demo-secret
      - ROUND=1
      - UPDATE_DIM=20
      - DP_ENABLED=true
      - DP_L2_CLIP=1.0
      - DP_NOISE_MULT=0.3
    networks:
      - edge_net

  silo_b2:
    build:
      context: ..
      dockerfile: silo-node/Dockerfile
    container_name: silo_b2
    environment:
      - NODE_ID=Silo_B2
      - COORDINATOR_URL=http://10.104.109.87:5000
      - PEERS=Silo_A1,Silo_A2,Silo_A3,Silo_B1,Silo_B2,Silo_B3
      - SHARED_SECRET=class-demo-secret
      - ROUND=1
      - UPDATE_DIM=20
      - DP_ENABLED=true
      - DP_L2_CLIP=1.0
      - DP_NOISE_MULT=0.3
    networks:
      - edge_net

  silo_b3:
    build:
      context: ..
      dockerfile: silo-node/Dockerfile
    container_name: silo_b3
    environment:
      - NODE_ID=Silo_B3
      - COORDINATOR_URL=http://10.104.109.87:5000
      - PEERS=Silo_A1,Silo_A2,Silo_A3,Silo_B1,Silo_B2,Silo_B3
      - SHARED_SECRET=class-demo-secret
      - ROUND=1
      - UPDATE_DIM=20
      - DP_ENABLED=true
      - DP_L2_CLIP=1.0
      - DP_NOISE_MULT=0.3
    networks:
      - edge_net

networks:
  edge_net:
    driver: bridge
    # The bridge driver by default manages outbound NAT allowing containers
    # to reach the host's external networks (e.g. WiFi) to contact 10.104.109.87
